info:
  description: A REST API to extend some of Shopify's features.
  title: Shopify Extension
  version: API version 1
paths:
    delete:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Delete address
      tags:
        - Address
    get:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get address
      tags:
        - Address
  'http://127.0.0.1:5000/article/2':
    delete:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Delete article
      tags:
        - Articles
  'http://127.0.0.1:5000/article/3':
    get:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get article
      tags:
        - Articles
    put:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: update article
      tags:
        - Articles
  'http://127.0.0.1:5000/article/product/2/article_id/5':
    post:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: New article for product
      tags:
        - Product
  'http://127.0.0.1:5000/auth/login':
    post:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: ''
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Login User
      tags:
        - Auth
  'http://127.0.0.1:5000/customer/':
    get:
      parameters:
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get all Customers
      tags:
        - Customer
  'http://127.0.0.1:5000/customer/1':
    get:
      parameters:
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get Customers for user
      tags:
        - Customer
    put:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: ''
          required: true
          type: string
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Update Customer
      tags:
        - Customer
  'http://127.0.0.1:5000/customer/2':
    delete:
      parameters:
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Delete Customer for user
      tags:
        - Customer
  'http://127.0.0.1:5000/habit/':
    get:
      parameters:
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get Habits
      tags:
        - Habits
  'http://127.0.0.1:5000/habit/4':
    put:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Update habit
      tags:
        - Habits
  'http://127.0.0.1:5000/habit/customer/1':
    get:
      parameters:
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get Habits for customers
      tags:
        - Habits
  'http://127.0.0.1:5000/habit/customer/1/habit/1':
    post:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: New habit for customer
      tags:
        - Habits
  'http://127.0.0.1:5000/note/':
    get:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get all note
      tags:
        - Notes
  'http://127.0.0.1:5000/note/1':
    get:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get note w/o customer id
      tags:
        - Notes
    put:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Update note
      tags:
        - Notes
  'http://127.0.0.1:5000/note/2':
    delete:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Delete note
      tags:
        - Notes
  'http://127.0.0.1:5000/note/customer/1':
    get:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get note
      tags:
        - Notes
  'http://127.0.0.1:5000/order/':
    get:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get orders
      tags:
        - Orders
  'http://127.0.0.1:5000/order/1':
    delete:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Delete order
      tags:
        - Orders
  'http://127.0.0.1:5000/order/customer/1':
    post:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: New Order
      tags:
        - Orders
  'http://127.0.0.1:5000/product/':
    get:
      parameters:
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get all products
      tags:
        - Product
    post:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Add product
      tags:
        - Product
  'http://127.0.0.1:5000/product/2/order/1':
    delete:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Delete product from order
      tags:
        - Product
    post:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Add product to order
      tags:
        - Product
  'http://127.0.0.1:5000/product/3':
    delete:
      parameters:
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Delete product
      tags:
        - Product
    get:
      parameters:
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get Product by id
      tags:
        - Product
  'http://127.0.0.1:5000/product/no_of_articles/2':
    put:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Update product number of articles
      tags:
        - Product
  'http://127.0.0.1:5000/product/product_date':
    get:
      parameters:
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: ' Get all products by date desc'
      tags:
        - Product
  'http://127.0.0.1:5000/product/product_price_information':
    get:
      parameters:
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get max price of products
      tags:
        - Product
  'http://127.0.0.1:5000/tag/':
    get:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get tags
      tags:
        - Tags
  'http://127.0.0.1:5000/tag/1':
    delete:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Delete tag
      tags:
        - Tags
  'http://127.0.0.1:5000/tag/{tag_id}':
    get:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get tag
      tags:
        - Tags
    put:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Update tag
      tags:
        - Tags
  'http://127.0.0.1:5000/tag/customer/1':
    get:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: Get tag for customer
      tags:
        - Tags
  'http://127.0.0.1:5000/tag/customer/1/tag_id/5':
    post:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: header
          name: Content-Type
          required: true
          type: string
        - description: ''
          in: header
          name: Authorization
          required: true
          type: string
      responses:
        '200':
          description: successful operation
      summary: New tag for customer
      tags:
        - Tags
schemes:
  - HTTP protocol
swagger: '2.0'
tags:
  - description: ''
    name: Orders
  - description: ''
    name: Tags
  - description: ''
    name: Notes
  - description: ''
    name: Customer
  - description: ''
    name: Address
  - description: ''
    name: Habits
  - description: ''
    name: Auth
  - description: ''
    name: Articles
  - description: ''
    name: Product
  - description: ''
    name: Shopify Extension
