"""3rd migration

Revision ID: 4509bfb33d27
Revises: bff5d1b5525c
Create Date: 2020-12-09 14:38:53.641274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4509bfb33d27'
down_revision = 'bff5d1b5525c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notes', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    # ### end Alembic commands ###
