"""4th migration

Revision ID: c65f4b139bdc
Revises: 4509bfb33d27
Create Date: 2020-12-10 11:49:43.238556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65f4b139bdc'
down_revision = '4509bfb33d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_articles',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], )
    )
    op.drop_column('orders', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('products_articles')
    # ### end Alembic commands ###
